# Generated by Django 4.1.3 on 2022-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='ContaTipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoPreco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoQuantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoQuantidade',
            field=models.IntegerField(),
        ),
    ]
