# Generated by Django 4.1.3 on 2022-11-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0002_alter_conta_contatipo_alter_produto_produtopreco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='ContaCardapio',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='CardapioConta',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.conta'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='CardapioProduto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.produto'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaBairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaCep',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaComplemento',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaNumero',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaRua',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaStatus',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoProduto',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.produto'),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoUsuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.conta'),
        ),
    ]
