# Generated by Django 4.1.3 on 2022-11-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0003_remove_conta_contacardapio_cardapio_cardapioconta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='CardapioConta',
            new_name='CardapioUsuario',
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaStatus',
            field=models.IntegerField(),
        ),
    ]
