# Generated by Django 4.1.3 on 2022-11-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0004_rename_cardapioconta_cardapio_cardapiousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='ContaNome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='conta',
            name='ContaTipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
