# Generated by Django 4.1.3 on 2022-11-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0006_alter_conta_contastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoNome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoDescricao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoNome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoPreco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ProdutoQuantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
