# Generated by Django 4.1.3 on 2022-11-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0007_produtodocarrinho_produtodocarrinhonome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoPreco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
