# Generated by Django 4.1.3 on 2022-11-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0009_alter_cardapio_cardapiousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoProduto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.produto'),
        ),
    ]
