# Generated by Django 4.1.3 on 2022-11-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0010_alter_produtodocarrinho_produtodocarrinhoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='CardapioProduto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='CardapioUsuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoProduto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoUsuario',
            field=models.IntegerField(),
        ),
    ]
