# Generated by Django 4.1.3 on 2022-11-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CupcakeApp', '0012_alter_cardapio_cardapiousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='CardapioProduto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.produto'),
        ),
        migrations.AlterField(
            model_name='produtodocarrinho',
            name='ProdutoDoCarrinhoUsuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CupcakeApp.conta'),
        ),
    ]
